name: verbadent
description: "Verbadent CareQuest Flutter application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  equatable: ^2.0.5
  riverpod_annotation: ^2.3.5
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/library/
    - assets/images/before_visit/

  fonts:
    - family: KumarOne
      fonts:
        - asset: fonts/KumarOne-Regular.ttf
          weight: 400
    - family: InstrumentSans
      fonts:
        - asset: fonts/InstrumentSans-Bold.ttf
          weight: 700
